### ISSUE TITLE
ExpectedException Cannot Be Chained After MethodRules

### ISSUE THREAD

**Issue by EarthCitizen** [junit-team/junit4#1106]
I recently had an issue with a 3rd-party Rule which extends MethodRule. This rule modified the runtime in a way in which the expectations set up in ExpectedException were erased by the time that the test actually ran. So my first thought was to just chain ExpectedException after the 3rd-party rule. As, it turns out this is not possible because the 3rd-party rule extends MethodRule.

I was able to wrap the MethodRule inside a TestRule, but you have to pass "this" to the constructor. And based on many conversations and other issues I have seen around this topic, there seems to be a general agreement that passing "this" to a TestRule constructor is ugly and undesirable and that being given access to the test class instance is helpful and reasonable. I immediately see this as useful for injecting values or processing other custom annotations.

After taking a look at the code, it seems that there needs to be a slight redesign of the rule system and that a simple patch would not suffice and discussion about possible redesigns would be needed to solve this issue.

My personal opinion is that there should be one interface for class rules, and once interface for test rules, and that the test rule should give you the instance of the test class. It does not seem to be best to continue on with two different interfaces that can be applied at the test level (MethodRule and TestRule).

Having access to the test-class instance for the test-level rules seems to provide the best options for what can be accomplished at that level. I am willing to help out in any way I can if there is a decision made on a course of action.

**Comment by kcooney** [comment]
@EarthCitizen There are many issues being discussed here. I'll try to take the issues one by one, but I think we should close this and redirect the conversation to the other related bugs.

1. ExpectedException not supporting chaining and being affected by other rules

I suspect that we'll make a Lambda-based exception API and deprecate `ExpectedException`.

2. Third-party libraries that use `MethodRule` so cannot be chained

Unfortunately,  the `MethodRule` API isn't compatible with `TestRule` so I don't see a way to support chaining. The options I see are either wrap the rule with a `TestRule` (quite ugly) or convince the third-party owner that you want to use their rule in a rule chain and/or at the test level, and therefore need a version of the API that implements `TestRule`

3. Implement a new API to replace and/or augment `TestRule` and `MethodRule`

I agree we should consider new APIs. I suggest adding to the discussion on #793

Adding a new API doesn't solve the problems that the third-party libraries implement `MethodRule`. It would probably be easier to convince them to add a `TestRule` API because `TestRule` has been around a while.

4. The test instance isn't passed to `TestRule`

This has been discussed in #351

**Comment by EarthCitizen** [comment]
Before doing lambda expressions as a mandatory part of the API, verify how many people are stuck on JDK7 for 2-3 more years :-) (hand raised)

**Comment by kcooney** [comment]
We aren't planning on requiring JDK 7 for JUnit 5 (we will likely require JDK 6).

**Comment by rschmitt** [comment]
As I pointed out in #1153, JUnit doesn't need to require JDK 8 to offer a Lambda-ready API.

**Comment by kcooney** [comment]
All issues are either tracked by other bugs no or have been resolved

(1) We are adding `assertThrows` and  `assertThrows` in 4.13
(2) Tracked by #1221
(3) See my first comment for this issue
(4) See my first comment for this issue
