### ISSUE TITLE
@BeforeClass requiring the method to be static is nonsense

### ISSUE THREAD

**Issue by subes** [junit-team/junit4#122]
Hi,

JUnit is the only testing Framework which requires @BeforeClass Annotated methods to be static. This makes @BeforeClass mostly useless für Enterprise Applications, because often you have to do a setUpOnce after the dependency injection has been done (e.g. Spring or some other Framework). 

As a workaround @Before with a boolean field and an initialized check is often used which is against the design of JUnits @Before, but is required because @BeforeClass is mutilated by design... 

Also see:
http://stackoverflow.com/questions/1052577/why-must-junits-fixturesetup-be-static

Best Regards
subes

**Comment by dougschroeder** [comment]
It's so frustrating to write an abstract unit test class to test DB calls with JUnit b/c of this.  If my abstract class only has one implementer this works fine, but as soon as we have 2 or more and they get run in parallel, we start having thread issues because of the static state variables we have to have (either that or we have to create new databases for each test which is kind of overkill and slows test execution time down).  I miss JUnit 3 and TestNG -- these are a better fit for these kinds of tests since it appears JUnit 4 will never be fixed to support this kind of test (abstract test classes that need to initialize state once for all tests in the implementing sub-class).

**Comment by kcooney** [comment]
@dougschroeder How did you do per-test-class initialization in JUnit3?

Instead of having a common base class for database tests, have you considered using`@ClassRule`?

**Comment by dougschroeder** [comment]
Actually, it looks like our JUnit 3 tests were not doing one-time initialization in non-static methods either.  Hi @kcooney, thank you for the quick response!  I was able to get a solution working in JUnit 4 that allows me to do class-level setup and teardown in non-static methods by extending BlockJUnit4ClassRunner and having my base test class extend an interface that allows it to setup and tear down via an instance method.  I used this blog article as a guide: 

http://saltnlight5.blogspot.com/2012/09/enhancing-spring-test-framework-with.html

I didn't know about `@ClassRule` -- will have to look at that some more.  Thanks.

**Comment by kcooney** [comment]
@dougschroeder while the solution on the blog post would allow a one-time setup to.happen in a non-static method, unless I am missing something, the one-time setup would have to store state in a static field if you want the data available in more that one test.

For the use case you give, you use need 1) a class extending `ExternalResource` that sets up your database, and 2) in classes needing a database, a static field of that type annotated with `@ClassRule`. No base test case needed.

**Comment by dougschroeder** [comment]
@kcooney can I use that without having to group my implementations into a Suite?  I'd like to define my base test class in a common jar and not have to know about the tests that extend my base class.

To work around having to store my state in a static field, I had the setup method in my interface return an object and added another method to my interface to pass that object to tests:

    public interface InstanceTestClassListener {
        Properties beforeClassSetup();
        void beforeTestSetup(Properties state);
        void afterClassSetup(Properties state);
    }

Not the most elegant solution, so I'd rather use `ExternalResource` and `@ClassRule` if I can use it outside of a Suite (it sounds like I can since it says `BlockJUnit4ClassRunner` will support `@ClassRule`).

**Comment by kcooney** [comment]
@dougschroeder you don't need to define a suite.

**Comment by kirenpillay** [comment]
Using the Rules annotation is very easy to use and solved the problem for me.

http://stackoverflow.com/a/24267763/3795456

**Comment by ekeeton** [comment]
Just use testNg - does not require methods annotated @BeforeClass to be static - problem solved the way it should be
