### ISSUE TITLE
I got an error in line 116 in MaxCore class

### ISSUE THREAD

**Issue by fcalderonnearsoft** [junit-team/junit4#1263]
When I was watching MaxCore class IntelliJ show me up the following error:

` Exception 'org.junit.runners.model.InitializationError' is never thrown in the corresponding try block`

![captura de pantalla de 2016-03-20 21 00 55](https://cloud.githubusercontent.com/assets/17256207/13910428/4a38bdf0-eedf-11e5-8079-fb98f5c8d7e9.png)

**Comment by avargas-nearsoft** [comment]
Are you trying to use an anonymous class? If so, then it seems that the exception won't never be thrown. However, if you made an simple instance of Suite, omitting the curly braces {...} (that creates an anonymous class) you would catch the InitializationError.

**Comment by marcphilipp** [comment]
Well, the `Suite` constructor` declares `InitializationError` because it calls `super(klass)` and its super-class `ParentRunner` might throw such an error in the case of validation errors.

If I change the `Suite` constructor's visibility temporarily to `public` and omit the local anonymous subclass, the error does not show up anymore. Thus, it looks like a bug in IntelliJ to me.
