### ISSUE TITLE
Could tests that don't match a category be considered 'ignored' so that they show up in the test summary?

### ISSUE THREAD

**Issue by moderatemisbehaviour** [junit-team/junit4#1284]
I have recently discovered the awesome `Category` annotation. I am using it to run particular subsets of a larger set of tests, in other words, I am ignoring all tests that are not relevant to my current test run.

It would be even more helpful to me if tests that were not run were marked as 'Ignored', so that they can be picked up in test summaries / reports. If I am skipping tests, I want to know exactly which ones.

I realise not everyone's use case may match mine, so perhaps there could be a boolean parameter could be passed for this.

What do you think? Am I misunderstanding the use case for the `Category` annotation?

**Comment by kcooney** [comment]
That would be difficult to do, since the `Categoies` runner is implemented as a `Filter`, so anything that isn't in the category is removed from the Runner hierarchy before any tests are run.

Ignored tests are tests that you asked to run but couldn't be run because they were temporarily disabled via the `@Ignore` annotation. When you are using `Categoies` you are only asking to run some tests.

Note that some IDEs use filters to implement "run this single test method". It might be confusing to show those other tests as ignored.


Perhaps JUnit 5 would have a way to differentiate filtered vs ignored.

**Comment by moderatemisbehaviour** [comment]
Thanks for the reply Kevin, I wanted to have a dig around in the code to see how much effort this would be to change, I can't find the category runner though [with the others](https://github.com/junit-team/junit4/tree/master/src/main/java/org/junit/runners) though.

**Comment by marcphilipp** [comment]
It's in the `experimental` package:
https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/experimental/categories/Categories.java

**Comment by kcooney** [comment]
I vote to close this, since ignored tests shouldn't be reported the same as tests you decided not to run.

**Comment by marcphilipp** [comment]
Agreed.
