### ISSUE TITLE
One Test Instance for each Parameter value

### ISSUE THREAD

**Issue by pussinboots** [junit-team/junit4#1327]
Hi,

i use the Parameterized together with Selenium to run each test for different browser. Works pretty well. 

Then i need the possibility to run different test case method on the same browser instance mostly for performance purpose. After a while i find the possibility to provide my own BlockJUnit4ClassRunnerWithParameters implementation. So it was quite simple to achieve what i need by just provide the needed BlockJUnit4ClassRunnerWithParameters implemnantation changes.

It also povided the possibility to annotate a static method with @AfterParam this method is called when the test case for a particullar parameter value is done. Now i share the short code.

       public class SingleInstanceRunnerWithParameters extends    BlockJUnit4ClassRunnerWithParameters {
	@Retention( RetentionPolicy.RUNTIME )
	@Target({ METHOD, ANNOTATION_TYPE })
	public @interface AfterParam {}
	
	public static class SingleInstanceRunnerWithParameterssFactory implements ParametersRunnerFactory {
		public Runner createRunnerForTestWithParameters(TestWithParameters test) throws InitializationError {
			return new SingleInstanceRunnerWithParameters(test);
		}
	}

	private Map<TestClass, Object> tests = new HashMap<>();

	public SingleInstanceRunnerWithParameters(TestWithParameters test) throws InitializationError {
		super(test);
	}

	@Override
	public Object createTest() throws Exception {
		Object testInstance = tests.get(getTestClass());
		if (testInstance == null) {
			testInstance = super.createTest();
			tests.put(getTestClass(), testInstance);
		}
		return testInstance;
	}
	
	@Override
	protected Statement classBlock(RunNotifier notifier) {
		Statement classBlock = super.classBlock(notifier);
		return withAfterParams(classBlock);
	}
	
        protected Statement withAfterParams(Statement statement) {
                List<FrameworkMethod> afters = getTestClass().getAnnotatedMethods(AfterParam.class);
                return afters.isEmpty() ? statement : new RunAfters(statement, afters, null);
        }
    }

**Comment by PeterWippermann** [comment]
Thanks for sharing your thoughts and your code. But it would be more helpful, if you would set up a pull request instead of an issue.

However, I think your code heads to the wrong direction. By caching the instances of the "test class" in createTest() you circumvent JUnit's principle of executing every test method on a "fresh" instance of that test class.

If you want to reuse parameter objects (i.e. browser instances in your case) in multiple test methods, you should find other ways to do so. As far is I can see, a single tuple of parameters is reused for all methods of a test case anyway.

Regarding @AfterParam: Is it different from @After or @AfterClass? And if so, wouldn't one also like to have @BeforeParam then?

**Comment by pussinboots** [comment]
Thanks for the feedback. I will think about what you said and open a pull request or at least put in an own repositrory.
