### ISSUE TITLE
Enforce order of @Before/@After annotated methods even when override is also annotated

### ISSUE THREAD

**Issue by paulduffin** [junit-team/junit4#1411]
I recently had a problem where a fix to a compiler that copied annotations from a method onto a synthetic bridge method created by the compiler changed the behavior of a test.

I had two classes, lets call them Base and Derived. Each of them had an @Before annotated method, lets call them baseBefore() and derivedBefore() respectively. The order in which they were executed was critical, Base.baseBefore() must be invoked prior to Derived.derivedBefore(). While the order of invocation of the methods within a class is not defined, @Before annotated methods on a base class are always invoked before such methods on a derived class so everything worked fine.

The Base class is package protected so a synthetic bridge method is created in Derived that overrides the Base.baseBefore() method. Previously, that method did not have any annotations so was ignored by JUnit. However, the fix to copy annotations onto the bridge method now causes JUnit to see that synthetic bridge method and that causes it to ignore the method from Base because it was shadowed by the synthetic method. That also changes the order in which the methods are invoked causing the tests to fail. 

A simple solution is to exclude synthetic methods from the ones returned by JUnit but it seems as though the existing logic is flawed. Basically, as implemented overriding an @Before annotated method will not change the method order but adding an @Before annotation to it could change the order.

It seems to me that even when overridden and annotated with @Before that an @Before method declared on the base class should be run before any methods on the derived class.

**Comment by kcooney** [comment]
I don't think I agree with the last sentence. If you override a `@Before` method you shouldn't annotate the method on the subclass with `@Before`.  If you do, then I am personally fine with the call order being undefined.

Personally, I recommend always making Before and After methods final. If subclasses need to change or replace the base class behavior, extract a non-final protected method and have your. Before/After method call the extracted method. My personal preference is to make the extracted method abstract or, if non-abstract, have it do nothing.

I can't speak to the compiler issue. Are there reasons outside of JUnit to copy the annotations?

**Comment by paulduffin** [comment]
The background for the compiler issue can be found at:
https://bugs.openjdk.java.net/browse/JDK-6695379
https://bugs.eclipse.org/bugs/show_bug.cgi?id=495396

The compiler change was not made with JUnit in mind, and they're certainly not going to revert it for JUnit.

I agree that making Before/After methods final is better but it's not possible in the specific case that I mentioned above because JUnit cannot invoke an @Before method on a package protected class. Marking the Base.baseBefore() method final would prevent the creation of the bridge method and so prevent JUnit from being able to access the method.

Adding final is not easy when converting from JUnit 3 based tests which rely on overriding setUp/tearDown methods. It would certainly complicate any automation that is done as it would have to identity overrides of the setUp method and rename them to something else and special case when the base class is package protected so as not to make it final.

Similarly, having an @Before/@After method on an overridden method change the order in which methods are run means that any automatic conversion from JUnit 3 to 4 would have to identity overrides of the setUp method and not add @Before annotations to them in order to prevent this issue arising in future.

The test that broke was one of hundreds that had just recently been converted from JUnit 3 to JUnit 4 so the above concerns are ones that we have to deal with.

Aside: While writing the above I realised that unless the annotations were copied onto the synthetic bridge method that JUnit would try and invoke the public method on the package protected class which should fail. I then started questioning how my test worked before the compiler started copying annotations. Further investigation revealed that the critical factor is Android. On Android it is possible to invoke a public method on a package protected class.

I just looked at the documentation for @Before and it does say the following:

> The @Before methods of superclasses will be run before those of the current class, unless they are overridden in the current class.

That is not strictly correct. Overriding an @Before method does not change the order of methods, only overriding AND annotating with @Before will change the order.

I think that there are a number of surprising behaviors here:

1. Changing a base class to package protected changes the method order
2. Explicitly adding an @Before annotation to an overridden method changes the order of method invocation

Irrespective of your decision on #2 I certainly think that #1 needs addressing.

**Comment by kcooney** [comment]
My apologies. It looks like the behavior is defined in JUnit, and JUnit is trying to do what you propose. See:

- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/TestClass.java#L87
- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/TestClass.java#L63
- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/FrameworkMember.java#L15
- https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/FrameworkMethod.java#L136

The tests for this functionality is here:

https://github.com/junit-team/junit4/blob/master/src/test/java/org/junit/tests/running/methods/AnnotationTest.java#L487

I modified that test so `SuperShadowing` is package scope, and the test still passed (even if i make `SuperShadowing` a top-level class). I pushed my changes to https://github.com/kcooney/junit/commit/541ee5e

One problem I did find is that if the base class is package scope and has a public `@Before` method that is not overrideen by the subclass then JUnit will not call it at all. I don't know what's going on here. JUnit finds the method, and tries to call it (using `Method.invoke(testClassInstance, new Object[0])`) and the method isn't even called.

Since you can reproduce the issue, could you please dig into why this code isn't working for you? Note I am testing from the 4.13 master code, so before testing your specific example you might want to try to reproduce my experiments on AnnotationTest on whichever version of JUnit you are using.

I wonder if `getDeclaredMethods()` is returning something unexpected when there are bridge methods.

**Comment by paulduffin** [comment]
That test simply checks to make sure that the @Before/@After methods are still called even after they've been overridden. As there is only one of each type they cannot check the order in which they are invoked. To do that SubShadowing would need to define its own @Before/@After tests that do not override any from SuperShadowing. I would not expect changing the visibility of SuperShadowing to have any impact on the behavior of SubShadowing because the latter does not have multiple @After/@Before methods.

I've not seen that issue with a method not being called. I have seen a slight flaw in my IDE where changing visibility on the base class does not correctly recompile the derived class so it does not have the appropriate synthetic bridge methods which lead to incorrect behavior. That may be the source of your problem.

**Comment by kcooney** [comment]
You are correct. That test does exercise shadowing (because the `@Before` method isn't called twice) and we have tests that ensure that super class `@Before` methods are called before sub-class `@Before` methods, but we didn't test the intersection.

I have created a potential fix in #1412 but this would be a change in behavior, and I don't know how large impact would be. The change impacts not only `@Before` and `@After` methods but `@Test` methods  as well as methods and fields annotated with `@Rule`.

**Comment by kcooney** [comment]
BTW, I think it's a bug that we ignore shadowed fields (for `@Rule` and `@ClassRule`) if both the field in the base class and the field in the subclass are annotated with the same annotation.

**Comment by paulduffin** [comment]
The fix in #1412 looks great (one small spelling mistake of @Befoer instead of @Before). One slight concern that I have is that your test could be working simply because of a fluke in the order of methods. It would be safer for your test to enforce an ordering that causes the test to fail without your change.

The 'shadowing' field issue also seems like a bug to me as fields aren't shadowed in Java but that bug is orthogonal to this one.

As for the change in behavior it seems as though all that you are doing is changing from an indeterminate order to a fixed order. Any test that relied on that indeterminate order is going to be flaky anyway. If your change breaks it then it will break it consistently. Better a consistently failing test that a flaky passing one.

**Comment by kcooney** [comment]
The current order wasn't indeterminate. The code searches for methods starting from the test class up the super-class chain, and if it sees a method in a super class that was shadowed by a previously-seen method, it ignores it. Very deterministic.

**Comment by kcooney** [comment]
While working on fixing the issue where JUnit could consider fields or static methods as shadowed, I realized that there is a second possible fix for the problem for JUnit's handling of bridge methods, and that's to ignore bridge methods when scanning methods (see pull #1413). Unlike the previous proposed fix (pull #1412) this wouldn't change the behavior of test classes that have a `@Before` method that is overridden in the sub-class that also annotates the method with `@Before`

I think either solution would be fine for tools that convert JUnit3-style tests to JUnit4-style tests, since JUnit3-style tests cannot have multiple `tearDown()` methods.


@marcphilipp would appreciate your opinion on which fix we should merge.

**Comment by paulduffin** [comment]
When I said the order was indeterminate I was referring to the order in which @Before methods within a class are called.

Say you have baseBefore() from the base class and three methods (derived1Before(), derived2Before(), derived3Before()) from the sub class all annotated with @Before. Then baseBefore() is called before any of the other methods but those methods can be called in any order.

If the baseBefore() was overridden by the derived class and annotated with @Before (either explicitly or implicitly) then baseBefore() is no longer called before all the derived class methods (as it was treated as a derived class method) so the order in which baseBefore() was called became indeterminate which was the cause of the test failure that highlighted this issue in the first place.

Whatever change is made to fix this will need to change the order in which the overridden baseBefore() is called from the current indeterminate order to before all methods from the subclass. For most test classes if the change causes a test failure it will simply be making an intermittent test failure happen consistently. The only classes for which that would not be true are those that enforce an ordering on the affected test class.

Given that the order is indeterminate it is possible that a test which attempts to check that order will pass by accident simply because the indeterminate order matches the expected order. Enforcing an explicit order on the methods within the class that is the opposite of that expected will ensure that the code is working properly by changing the order.

So, if you order the above alphabetically then the correct order, as checked by the test should be - baseBefore(), derived3Before(), derived2Before(), derived1Before().

However, without your change the methods would be invoked in the following sequence - derived3Before(), derived2Before(), derived1Before(), baseBefore() which would always cause the test to fail.

Either fix would be find but I think the one that provides consistent behavior whether the method is added explicitly by the developer or implicitly by the compiler would be better. Deleting an override or adding an override should not change the order of method calls from indeterminate to determinate or vice versa.

**Comment by kcooney** [comment]
For the case where the method is added explicitly by the developer, it is not the override that causes the change in calling order; it's overriding _and annotating the method with `@Before` and `@After`_. If you just override, you get the behavior you eant, because you are simply changing the behavior of the method in the subclass.

We could argue back and forth as to what the behavior should have been, but pull 1412 is a change in behavior for code that the developer explicitly wrote (not judging, just clarifying). Let's let Marc decide if we only want to fix the issue with bridge methods or if we should change the behavior in general.

Paul, I suggest you add an error prone check in your code base for classes that override methods annotated with `@Before` or `@Adter` if the subclass method is also annotated.

**Comment by marcphilipp** [comment]
I'm fine with either #1412 or #1413. It sounds like you're more comfortable with #1413 but I'll let you make the choice. 🙂

**Comment by kcooney** [comment]
Incidentally, both changes could lead to what Paul is calling "indeterminate behavior". If a base class has two `@Before` methods and a subclass overrides one of them and annotates the overridden method with `@Before` then the order that the before messages are called is currently defined (and would remain so with #1413) but will become indeterminate with #1412 

In short, if a class has multiple `@Before` methods or multiple `@After` methods then the developer should not expect a specific order.

I like the simplicity of the code in #1412 but I would rather not change the behavior of the case when the developer explicitly wrote the overridden method, because 1) the developer's intent is unclear and 2) in many cases the current behavior is deterministic.

@marcphilipp I recommend looking into JUnit5's behavior for bridge methods (and possibly also for shadowed methods).

**Comment by marcphilipp** [comment]
So, will you merge #1413?

> I recommend looking into JUnit5's behavior for bridge methods (and possibly also for shadowed methods).

Thanks, will do!

**Comment by kcooney** [comment]
> So, will you merge #1413?

Done.

I'll be sending a pull for the issue with fields and static methods hopefully soon.
