### ISSUE TITLE
Consideration of create a new annotation to be executed before of @Parameters

### ISSUE THREAD

**Issue by manueljordan** [junit-team/junit4#1434]
## Overview

I have assumed that `@BeforeClass` is executed before of `@Parameters`. 
I did realize it is not true. 

## Situation

The situation is that `@Parameters` needs mandatorily data initializated from `@BeforeClass`. 

Now, because my original assumption was wrong, my unique way to around this is through a `static` block to accomplish my goal.

## Original Proposal

Assuming this behaviour is the expected. Create a new annotation to accomplish the following order:

* `@NewAnnotation` such as "@BeforeParameter"
* `@Parameter`
* `@BeforeClass`
* `@Before`
* `@Test`

**Comment by kcooney** [comment]
Unfortunately, JUnit needs to call `@Parameters` methods very early so it can enumerate all the test cases (which is done before any tests are run). The `@BeforeClass` and `@ClassRule` members for each class are called/applied right before the tests in their corresponding class are started.

Could you initialize your data in the `@Parameters` method?

**Comment by manueljordan** [comment]
Thanks by the explanation. 

> Could you initialize your data in the @Parameters method?

It depends of the following: How many times the `@Parameters` method is executed?
I am assuming just one (how a `static` block) and the Test Class constructor is called N times according the number of items added in the `@Parameters` method. Am I correct?

Because I had that doubt, having the intention to save resources and time about testing, I use the `static` block. I am ok with this "work around solution". I confirmed this approach in Stack Overflow.

**Comment by kcooney** [comment]
I am personally not a fan of doing initialization that could fail in static blocks. If code in a static block throws an exception, the class fails to load, and the resulting exceptions can be confusing.

If you want the initialization to happen once even if the `@Parameters` method is called multiple times, make the method synchronized and store the result of your initialization in a static volatile field (or a final field of type `AtomicReference`).

**Comment by manueljordan** [comment]
Thanks by your perspective. I understand and I am agree. 

But in my `static` block is created a lot of data that has no relation with infrastructure data (DataSource, JMS connections), the data created is expensive in some way.

Thus because that data can't be created in `@BeforeClass` it is created in a `static` block

**Comment by kcooney** [comment]
@manueljordan can you enumerate how many parameters your `@Parameters` method will return without doing the expensive initialization?

If so, you could do something like this:

```
@ClassRule
public static final MyRule myRule = new MyRule();

@Parameters
public static List<Integer> data() {
    return IntStream.range(0, NUM_ITEMS).collect(Collectors.toList());
}

public MyTest(int index) {
  myData = myRule.getMyDataByIndex(index);
}
```

If you cannot know the number of parameters at the time the `@Parameters` metrhod is called, then you'll have to do the expensive initialization in the `@Parameters`  method. I don't think adding another JUnit annotation helps much here.

The `@Parameters` method will get called only once per class annotated with `@RunWith(Parameterized.class)` so you usually don't need to make the method `synchronized`. The only time it could be called multiple times is if you create a suite that includes the test class multiple times (this is not recommended, since `RunListener` doesn't provide a good way to know which version of the test is being run). 

JUnit 5 will support dynamic tests, which will provide a cleaner way to do what you want. See https://dzone.com/articles/junit-5-dynamic-tests-generate-tests-at-run-time to learn more.

Given that there are reasonable work-arounds in JUnit 4 and much better support in JUnit 5, I'm going to close this issue. Please feel free to continue discussion here if you need help doing what you want in a JUnit 4 Parameterized test.
