### ISSUE TITLE
Cannot download javadoc package list from JUnit web site

### ISSUE THREAD

**Issue by ilya-g** [junit-team/junit4#1500]
I'm trying to get javadoc package list from this url http://junit.org/junit4/javadoc/latest/package-list using `HttpURLConnection`. This results in the following request being issued:

```
GET http://junit.org/junit4/javadoc/latest/package-list HTTP/1.1
User-Agent: Java/1.8.0_144
Host: junit.org
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
```

Then this request gets rejected with 403 error and the following body

> Error 1010 Ray ID: 3e9f21c3f0ae871b • 2018-02-08 14:03:21 UTC 
> 
> Access denied
> What happened?
> The owner of this website (junit.org) has banned your access based on your browser's signature (3e9f21c3f0ae871b-ua21).

Obviously, I could change the User-Agent header to something else, but the question is why do you prohibit that default Java user-agent header in the first place?

**Comment by stefanbirkner** [comment]
We are using [GitHub pages](https://pages.github.com/) for the JUnit website. Unfortunately we are not in control of this problem.

**Comment by ilya-g** [comment]
Yes, I'd tried HTTPS, it didn't help either.

**Comment by panchenko** [comment]
That's protection from [cloudflare](https://www.cloudflare.com/), might be they classify java as a [bot](https://www.cloudflare.com/security/malicious-bot-abuse/).

**Comment by marcphilipp** [comment]
I've disabled Cloudflare's Browser Integrity Check.

@ilya-g Can you please try again?

**Comment by sbrannen** [comment]
It works for me; however, my browsers (tried on Firefox and Safari) download the `package-list` as a TEXT file instead of displaying it within the browser (as a text file).

Contrast this behavior with the behavior for Spring's latest `package-list`: https://docs.spring.io/spring/docs/5.0.3.RELEASE/javadoc-api/package-list

That one displays within my browser, so I'm wondering if Cloudfare is somehow interfering with this.

**Comment by ilya-g** [comment]
@marcphilipp Now it's fine, thank you!
