### ISSUE TITLE
@Parameters-Method is called even if category is excluded

### ISSUE THREAD

**Issue by nstng** [junit-team/junit4#1636]
Hi,

starting with 4.13-beta-n test that run with Parameterized can be categorized. If I exclude certain categories then it seems the @Parameters-Method of respective tests is called. E.g., the following Gradle task fails with an AssertionError.

```
task myTest(type: Test) {
    useJUnit() {
        excludeCategories "my.path.MyCategory"
    }
}
```

```
@Category({MyCategory.class})
@RunWith(Parameterized.class)
public class MyTest {

    public MyTest(int number) { }

    @Parameters
    public static Collection<Object[]> data() {
        fail();
        return Arrays.asList(new Object[][] {{1}});
    }

    ...
}
```

I would expect that data() is not called if the test class is annotated with the excluded category. I see the same behavior with 4.13-rc-1.

Best, n

**Comment by marcphilipp** [comment]
`Parameterized` calls the `@Parameters` method eagerly in its constructor. But even if it were called lazily, its base class `ParentRunner` only calls passed in `Filters` with its children. Thus, I don't see us changing that.

@kcooney @stefanbirkner WDYT?

**Comment by kcooney** [comment]
I'm not sure how this could be fixed.

 Inclusion and inclusion of Categories is done by special filters. The way filtering works in JUnit4 is that you call one of the static methods in `Request` to create a `Request`. You then call `Request.filterWith(Filter)` to do the filtering. The `Filter` class is passed the `Description` objects that represent nodes in the test tree. To do the filtering, the top-level `Description` needs to be passed into the filter. Since a `Description` has a hard reference to its direct children, you need to build the entire `Description` tree to do the filtering.

For the Parameterized runner, the parameters are used to implement the Description tree. In order to do any filtering, we need to build the tree, and to build the tree, we need to know the parameters.

**Comment by marcphilipp** [comment]
I'm closing this issue since there's no way to fix it without fundamental changes to JUnit 4.

**Comment by PrasanthV454** [comment]
@marcphilipp has this been changed in JUnit 5?

**Comment by marcphilipp** [comment]
JUnit 5 (Jupiter) currently only supports parameterizing test methods. If such a method is annotated with `@Disabled`, the parameter providing method (when using `@MethodSource`) is indeed not called.
