### ISSUE TITLE
More Concise Error Message In Tests

### ISSUE THREAD

**Issue by stevewhitmore** [junit-team/junit4#1640]
It would be really useful to be able to add an additional argument to the `@Test` annotation to assert an error was thrown with a certain message instead of instantiating a new class and then calling a method on it.

ExpectedException is an okay workaround but it would be much more concise as 

```java
@Test (expected = RuntimeException.class, message = "Employee ID is null")
public void shouldThrowRuntimeExceptionWhenEmployeeIDisNull() { ... }
```

as discussed here: https://stackoverflow.com/questions/2469911/how-do-i-assert-my-exception-message-with-junit-test-annotation

**Comment by panchenko** [comment]
The JUni 4.13 / 5 solution is mentioned there https://stackoverflow.com/a/52085072/826958
Having message in the annotation is not flexible enough.

**Comment by stefanbirkner** [comment]
We don't recommend to use `@Test(expected=...)` anymore because there are better alternatives. Therefore we don't improve support for this type of exception testing. Here are two alternatives that come with JUnit 4. Assertion libraries like AssertJ have support for exception testing, too.

JUnit 4 provides the [ExpectedException](https://junit.org/junit4/javadoc/latest/org/junit/rules/ExpectedException.html)

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Test
    public void shouldThrowRuntimeExceptionWhenEmployeeIDisNull() {
      thrown.expect(RuntimeException.class)
        .reportMissingExceptionWithMessage("Employee ID is null");
      ...
    }

and with JUnit 4.13 and Java 8 you can use [assertThrows](https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThrows(java.lang.Class,%20org.junit.function.ThrowingRunnable))

    @Test
    public void shouldThrowRuntimeExceptionWhenEmployeeIDisNull() {
      assertThrows(
        "Employee ID is null",
        RuntimeException.class,
        () -> ...
      );
    }

**Comment by stevewhitmore** [comment]
Thanks @panchenko and @stefanbirkner. I learned something new today. Appreciate the responses!
