### ISSUE TITLE
@Autowired doesn't seem to work in JUnit Test Cases while Running via ANT

### ISSUE THREAD

**Issue by sshanmu91** [junit-team/junit4#1680]
@Autowired doesn't seem to work in JUnit Test Cases while Running via ANT.

JUnit Test Cases are Failing while executing through ANT while it's Successful when executing the Test Case in Eclipse.

ANT Version - ANT 1.9x
JUnit4
Java8
Spring5

Could anyone please provide a resolution for this issue.

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
