### ISSUE TITLE
ExpectedException - Intended supported java version?

### ISSUE THREAD

**Issue by boaks** [junit-team/junit4#1684]
I'm currently struggling with the deprecation of `ExpectedException.none()`. 
Using/supporting Java 7 and updating from 4.12 to 4.13 causes deprecation warnings.
Therefore I started to search, which junit version supports which java version.
I didn't found something. Is there a list?  

Using `Assert.assertThrows` and `Runnable`with java 7 seem for me to be just "pain".
Is this really intended to be used for java 7? Or is java 7 not supported for that 4.13?

**Comment by marcphilipp** [comment]
Deprecating `ExpectedException.none()` instead of the entire class was a compromise that resulted from the discussion in #1609. While discouraged, you may continue to use `ExpectedException`. If you'd like to avoid suppressing the deprecation warning in all usage sites, you could create your own factory method as suggested in https://github.com/junit-team/junit4/issues/1609#issuecomment-543877082. Another approach that I've seen in quite a few projects, is to use a different source level in test code, e.g. Java 8, which would allow you to use `assertThrows` without the pain. For example, in the junit5 repo, we use Java 8 for our main sources, but Java 15 for tests.

**Comment by boaks** [comment]
Thanks!
